baseURL = 'https://moatazbadawy.github.io/'
languageCode = 'en-us'
title = 'Moataz Badawy'
theme = 'hugo-theme-stack'

[module]
  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"

# Menu configuration
[menu]
    [[menu.social]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/moataz-badawy/"
        [menu.social.params]
            icon = "linkedin"

    [[menu.social]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/MoatazBadawy"
        [menu.social.params]
            icon = "brand-github"
        
    [[menu.social]]
        identifier = "cv"
        name = "Resume/CV"
        url = "https://drive.google.com/file/d/1BKniH9ShG79CAn-ifU96zFUHSBogm7f8/view?usp=sharing"
        [menu.social.params]
            icon = "cv"

# Site parameters
[params]
    mainSections = ["post"]
    featuredImageField = "image"
    rssFullContent = true
    
    [params.footer]
        since = 2020
        customText = ""

    [params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"

    [params.article]
        math = false
        toc = true
        readingTime = true

    [params.comments]
        enabled = yes
        provider = "disqus"

    [params.sidebar]
        subtitle = "Make it happen with code 🚀"
        [params.sidebar.avatar]
            enabled = true
            local = false
            src = "/img/gogo.png"

    [params.widgets]
        homepage = [
            {type = "search"},
            {type = "archives", params = { limit = 5 }},
            {type = "tag-cloud", params = { limit = 10 }}
        ]
        page = [
            {type = "toc"}
        ]

    customCSS = ["css/custom.css"]

    # Simple favicon configuration - Stack theme expects a single string
    favicon = "/favicon/favicon.ico"

# Related content configuration
[related]
    includeNewer = true
    threshold = 60
    toLower = false
    
    [[related.indices]]
        name = "tags"
        weight = 100
    
    [[related.indices]]
        name = "categories"
        weight = 80
    
    [[related.indices]]
        name = "date"
        weight = 10

[markup]
    [markup.tableOfContents]
        endLevel = 4
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = false
        codeFences = true
        guessSyntax = true
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 4